# Generated by Django 5.2.7 on 2025-10-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject')},
        ),
    ]
